### PR TITLE
fix: add utils for handling jvs public key, and remove duplicate keys

### PR DESCRIPTION
**Pull request by sailorlqh**
fix issue: #391

### CODE REVIEW

**Comment by yolocs** [comment]
I don't think we should add this test key to non-test code. Anything under `clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/` is non-test code.

Plus, the public / private key used in integration test are shared across Go and Java. I think the proper fix should be:

1) Put the keys in files under `integration` folder
2) Update the test app dockerfiles to copy the public key into the container image
3) Update the test apps to use read the public key file
4) Update integration test to accept the test private key as a config.

cc: @capri-xiyue

**Comment by capri-xiyue** [comment]
Agree that we should not add this test key to non-test code

**Comment by capri-xiyue** [comment]
> I don't think we should add this test key to non-test code. Anything under `clients/java-logger/library/src/main/java/com/abcxyz/lumberjack/auditlogclient/` is non-test code.
> 
> Plus, the public / private key used in integration test are shared across Go and Java. I think the proper fix should be:
> 
> 1. Put the keys in files under `integration` folder
> 2. Update the test app dockerfiles to copy the public key into the container image
> 3. Update the test apps to use read the public key file
> 4. Update integration test to accept the test private key as a config.
> 
> cc: @capri-xiyue

Yes, we should not add this test key to non-test code

**Comment by sqin2019** [comment]
@yolocs As an improvement, should we put this JWKHandler in JVS pkg as a test util?

**Pull request closed without merging**
